[ids]
*
# Corne Vial uses its own firmware and per-device XKB map.
-4653:0004

[main]
# Define que o Alt Direito (AltGr) ativa nossa camada personalizada
rightalt = layer(meu_altgr)
alt = layer(meu_atalho)

[meu_altgr:G]
# Mapeia a tecla 'm' para o macro til
# O comando macro(~) digita o caractere explicitamente
m = macro(~)

[meu_atalho:A]
# Simula: Shift + ` (~) seguido da letra
# Isso assume que seu layout de teclado no Linux é US International
a = macro(S-grave a)
o = macro(S-grave o)
e = macro(S-6 e)
left = home
right = end
up = pageup
down = pagedown
backspace = macro(home S-end backspace)
